In [12]:
import pandas as pd

In [13]:
path = "/Users/VLADIMIR/Downloads/cars.csv"
data = pd.read_csv(path, encoding = 'utf-8')

print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [14]:
import os
print ("The directory we are working in is:{}".format(os.getcwd()))

The directory we are working in is:C:\Users\VLADIMIR

In [19]:
data = pd.read_csv('cars.csv')
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [20]:
data

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,False,False,True,True,301
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,True,False,False,True,True,False,False,True,True,317
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,False,False,True,True,369
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,True,False,False,False,False,False,False,False,True,490
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,False,False,False,False,False,False,True,632

In [21]:
data.shape

(38531, 30)

In [24]:
data.describe

<bound method NDFrame.describe of       manufacturer_name  model_name transmission   color  odometer_value  \
0                Subaru     Outback    automatic  silver          190000
1                Subaru     Outback    automatic    blue          290000
2                Subaru    Forester    automatic     red          402000
3                Subaru     Impreza   mechanical    blue           10000
4                Subaru      Legacy    automatic   black          280000
...                 ...         ...          ...     ...             ...
38526          Chrysler         300    automatic  silver          290000
38527          Chrysler  PT Cruiser   mechanical    blue          321000
38528          Chrysler         300    automatic    blue          777957
38529          Chrysler  PT Cruiser   mechanical   black           20000
38530          Chrysler     Voyager    automatic  silver          297729

       year_produced engine_fuel  engine_has_gas engine_type  engine_capacity  \
0               2010    gasoline           False    gasoline              2.5
1               2002    gasoline           False    gasoline              3.0
2               2001    gasoline           False    gasoline              2.5
3               1999    gasoline           False    gasoline              3.0
4               2001    gasoline           False    gasoline              2.5
...              ...         ...             ...         ...              ...
38526           2000    gasoline           False    gasoline              3.5
38527           2004      diesel           False      diesel              2.2
38528           2000    gasoline           False    gasoline              3.5
38529           2001    gasoline           False    gasoline              2.0
38530           2000    gasoline           False    gasoline              2.4

       ... feature_1  feature_2 feature_3 feature_4  feature_5  feature_6  \
0      ...      True       True      True     False       True      False
1      ...      True      False     False      True       True      False
2      ...      True      False     False     False      False      False
3      ...     False      False     False     False      False      False
4      ...      True      False      True      True      False      False
...    ...       ...        ...       ...       ...        ...        ...
38526  ...      True      False     False      True       True      False
38527  ...      True      False     False      True       True      False
38528  ...      True      False     False      True       True      False
38529  ...      True      False     False     False      False      False
38530  ...     False      False     False     False      False      False

      feature_7  feature_8  feature_9  duration_listed
0          True       True       True               16
1         False      False       True               83
2         False       True       True              151
3         False      False      False               86
4         False      False       True                7
...         ...        ...        ...              ...
38526     False       True       True              301
38527     False       True       True              317
38528     False       True       True              369
38529     False      False       True              490
38530     False      False       True              632

[38531 rows x 30 columns]>

In [26]:
data['color'].describe()

count     38531
unique       12
top       black
freq       7705
Name: color, dtype: object

In [39]:
cut_data = data.iloc[0:10, :]
cut_data

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7
5,Subaru,Outback,automatic,silver,132449,2011,gasoline,False,gasoline,2.5,...,True,False,False,False,True,False,True,True,True,67
6,Subaru,Forester,automatic,black,318280,1998,gasoline,False,gasoline,2.5,...,True,False,False,True,True,False,False,True,True,307
7,Subaru,Legacy,automatic,silver,350000,2004,gasoline,False,gasoline,2.5,...,True,True,False,False,False,False,False,False,True,73
8,Subaru,Outback,automatic,grey,179000,2010,gasoline,False,gasoline,2.5,...,True,True,True,True,True,True,True,True,True,87
9,Subaru,Forester,automatic,silver,571317,1999,gasoline,False,gasoline,2.5,...,True,True,False,False,True,False,False,False,True,43

In [40]:
new_data = ['used', 'used', 'new', 'new', 'used', 'used', 'used', 'used', 'used', 'used']
cut_data.insert(1, 'New', new_data)
cut_data

,manufacturer_name,New,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,used,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,used,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,new,Forester,automatic,red,402000,2001,gasoline,False,gasoline,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,new,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,used,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,...,True,False,True,True,False,False,False,False,True,7
5,Subaru,used,Outback,automatic,silver,132449,2011,gasoline,False,gasoline,...,True,False,False,False,True,False,True,True,True,67
6,Subaru,used,Forester,automatic,black,318280,1998,gasoline,False,gasoline,...,True,False,False,True,True,False,False,True,True,307
7,Subaru,used,Legacy,automatic,silver,350000,2004,gasoline,False,gasoline,...,True,True,False,False,False,False,False,False,True,73
8,Subaru,used,Outback,automatic,grey,179000,2010,gasoline,False,gasoline,...,True,True,True,True,True,True,True,True,True,87
9,Subaru,used,Forester,automatic,silver,571317,1999,gasoline,False,gasoline,...,True,True,False,False,True,False,False,False,True,43

In [42]:
cut_data.groupby('New').describe()

     odometer_value                                                          \
              count       mean            std       min       25%       50%
New
new             2.0  206000.00  277185.858225   10000.0  108000.0  206000.0
used            8.0  288880.75  136681.229104  132449.0  187250.0  285000.0

                         year_produced            ... up_counter         \
           75%       max         count      mean  ...        75%    max
New                                               ...
new   304000.0  402000.0           2.0  2000.000  ...       64.5   72.0
used  326210.0  571317.0           8.0  2004.375  ...       54.5  147.0

     duration_listed
               count     mean        std   min     25%    50%     75%    max
New
new              2.0  118.500  45.961941  86.0  102.25  118.5  134.75  151.0
used             8.0   85.375  94.391188   7.0   36.25   70.0   84.00  307.0

[2 rows x 56 columns]